#!/bin/bash
system=""
if [ "$(uname)" == "Darwin" ]; then
    system="mac"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    system="linux"
fi

function bootstrap_bash {
    echo "Bootstraping bashrc files..."
    mkdir -p ~/.bash
    ln -f -s "$(pwd)/bash/bash_others" ~/.bash/bash_others
    ln -f -s "$(pwd)/bash/bash.$system" ~/.bash/bash.system

    if [ "$system" == "linux" ]; then
        if [ -f ~/.bashrc ]; then
            mv ~/.bashrc ~/bashrc.backup
        fi
        ln -s "$(pwd)/bash/bashrc" ~/.bashrc
    elif [ "$system" == "mac" ]; then
        if [ -f ~/.bash_profile ]; then
            mv ~/.bash_profile ~/bash_profile.backup
        fi
        ln -s "$(pwd)/bash/bashrc" ~/.bash_profile
    fi
    echo "Done."
}

function bootstrap_vim {
    echo "Bootstraping vim files"
    # Install vim-plug
    if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
    # Create symlink for .vimrc
    if [ -f ~/.vimrc ]; then
        mv ~/.vimrc ~/vimrc.backup
    fi
    ln -s "$(pwd)/vim/vimrc" ~/.vimrc
    echo "Done."
}

function bootstrap_tmux {
    echo "Bootstraping tmux files"
    if [ -f ~/.tmux.conf ]; then
        mv ~/.tmux.conf ~/tmux.backup
    fi
    ln -s "$(pwd)/tmux/tmux.conf" ~/.tmux.conf
    echo "Done."
}

function bootstrap_git {
    echo "Bootrapping git files"
    if [ -f ~/.gitignore ]; then
        mv ~/.gitignore ~/gitignore.backup
    fi
    ln -s "$(pwd)/git/gitignore" ~/.gitignore
    echo "Done."
}

function bootstrap_i3 {
    echo "Bootstrapping i3 files"
    if [ -d ~/.config/i3 ]; then
        mv ~/.config/i3 ~/i3.backup
    fi
    mkdir ~/.config/i3
    ln -s "$(pwd)/i3/config" ~/.config/i3/config
    if [ -f ~/.i3status.conf ]; then
        mv ~/.i3status.conf ~/i3status.conf.backup
    fi
    ln -s "$(pwd)/i3/i3status.conf" ~/.i3status.conf
}

function bootstrap_terminator {
    echo "Bootstrapping terminator files"
    if [ -d ~/.config/terminator ]; then
        mv ~/.config/terminator ~/terminator.backup
    fi
    mkdir ~/.config/terminator
    ln -s "$(pwd)/terminator/config" ~/.config/terminator/config
}

echo "Bootstraping dotfiles into machine."
bootstrap_bash
bootstrap_vim
bootstrap_tmux
bootstrap_git
bootstrap_i3
bootstrap_terminator
